mooncake/account/urls.py
from django.urls import path

from .views import (
    LogInView, SignUpView, ActivateView, LogOutView,
    ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'account'

urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),


    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
]

mooncake/ask/urls.py
from django.urls import path


from .views import index


app_name = 'ask'

urlpatterns = [
    path('', index, name='index'),
]

mooncake/mooncake/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from node import views


router = routers.DefaultRouter()
router.register(r'nodes', views.NodeViewSet)


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('account/', include('account.urls')),
    path('ask/', include('ask.urls')),
]

mooncake/templates/layout/default.html
{% load static %}
{% load compress %}

{% load node_extras %}


<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no"
    />
    <title>farseek.top</title>
    {% compress css %}
      <link rel="stylesheet" type="text/x-scss" href="{% static 'style/main.scss' %}" />
    {% endcompress %}

    {% compress js %}
      <script src="{% static 'vendor/jquery/jquery-3.4.1.slim.min.js' %}"></script>
      <script src="{% static 'js/main.js' %}" type="text/javascript" charset="utf-8"></script>
    {% endcompress %}

  </head>

  <body>

    <header>
      <div class="top d-flex align-items-center {{ request.path|header_top_style }}">
        <div class="container d-flex">
          <a href="/" class="logo">Farseek</a>

          <div class="menu d-flex justify-content-between align-items-center w-100">
            <ul class="left">
              <li>
                <a href="/">首页</a>
              </li>
              <li>
                <a href="/ask">问答</a>
              </li>
            </ul>

            <ul class="right">
              {% if user.is_authenticated %}
              <li><a href="{% url 'account:logout' %}">退出</a></li>
              {% else %}
                <li><a href="{% url 'account:login' %}">登录</a></li>
                <li><a href="{% url 'account:signup' %}">注册</a></li>
              {% endif %}
            </ul>
          </div>

          
        </div>
      </div>
    </header>

    <div class="center">
      <div class="container d-flex">

        {% block content %}
        {% endblock %}

      </div>
      
    </div>


    <footer>

      <div class="container">
        <ul class="d-flex justify-content-center">
          <li><a href="">关于我们</a></li>
          <li><a href="">联系我们</a></li>
        </ul>
      </div>
      
    </footer>

  </body>
</html>